pipeline:

  #backend:
  #  image: node:9
  #  pull: true
  #  when:
  #    event: push
  #  commands:
  #    - yarn
  #    - ./test-server.sh

  frontend:
    image: node:9
    pull: true
    when:
      event: push
    commands:
      - yarn
      - npm run build

  deploy-dev:
    image: drillster/drone-rsync
    hosts: [ ascendntnu.no ]
    key: ${RSYNC_KEY}
    secrets: [ rsync_key ]
    target: /home/ascend/ascendntnu-web
    when:
      status: success
      event: push
      branch: dev
    script:
      - cd /home/ascend/ascendntnu-web
      - DOCKER_USER= docker-compose run build
      - source .env.development.local
      - DOCKER_PORT=$DOCKER_PORT DOCKER_API_PORT=$DOCKER_API_PORT docker-compose up --no-deps --force-recreate -d server api db

  deploy-prod:
    image: drillster/drone-rsync
    hosts: [ ascendntnu.no ]
    key: ${RSYNC_KEY}
    secrets: [ rsync_key ]
    target: /home/ascend/ascendntnu-web-prod
    when:
      status: success
      event: tag
      branch: dev
    script:
      - cd /home/ascend/ascendntnu-web-prod
      - DOCKER_USER= docker-compose run build
      - source .env.production.local
      - DOCKER_PORT=$DOCKER_PORT DOCKER_API_PORT=$DOCKER_API_PORT docker-compose up --no-deps --force-recreate -d server api db
