pipeline:
  backend:
    image: registry.ascendntnu.no/ascend-web-baseimage:latest
    pull: true
    when:
      event: push
      branch: dev
    commands:
      - cp -R /ascend-web/node_modules .
      - cp constants-example.js constants.js
      - ./test-server.sh
  frontend:
    image: registry.ascendntnu.no/ascend-web-baseimage:latest
    pull: true
    when:
      event: push
      branch:
        include: [ dev, feature/* ]
    commands:
      - cp -R /ascend-web/node_modules .
      - cp constants-example.js constants.js
      - webpack
  deploy:
    image: appleboy/drone-ssh
    host: ascendntnu.no
    user: root
    key: ${SSH_KEY}
    secrets: [ ssh_key, test ]
    environment:
      - DRONE_TAG=${DRONE_TAG}
    when:
      event: push
      branch: test
    script:
      - echo $DRONE_TAG
      - echo ${DRONE_TAG}
      - echo ${DRONE_COMMIT_SHA:0:8}
