pipeline:
  backend:
    image: registry.ascendntnu.no/ascend-web-baseimage
    when:
      event: push
      branch: dev
    commands:
      - cp constants-example.js constants.js
      - ./test-server.sh