pipeline:
  backend:
    image: registry.ascendntnu.no/aascend-web-baseimage:latest
    pull: true
    when:
      event: push
      branch: dev
    commands:
      - cp constants-example.js constants.js
      - ./test-server.sh
