pipeline:
  backend:
    image: ascend/ascend-web-baseimage
    when:
      event: push
      branch: dev
    commands:
      - npm install --silent --depth=0
      - cp constants-example.js constants.js
      - ./test-server.sh
