FROM node:6

RUN apt-get update
RUN apt-get install vim -y
RUN npm i -g typescript typings webpack --silent --depth=0

ENV APP_DIR /ascend-web

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR
ADD package.json ./
RUN npm install --depth=0 --quiet

VOLUME $APP_DIR

CMD ["pm2", "start", "server.js", "--no-daemon"]
