version: '2'

services:
  ascend:
    build:
      context: .
      dockerfile: Dockerfile.compose
    command: ./deploy.sh
    ports:
      - ${PORT_IN}:${PORT_OUT}
    volumes:
      - .:/ascend-web/:rw
    working_dir: /ascend-web
