FROM node:6

RUN apt-get update
RUN apt-get install vim -y

RUN mkdir /ascend-web
WORKDIR /ascend-web
ADD package.json ./
RUN npm install --silent
RUN npm i -g pm2 typescript typings webpack --silent
