version: '3'

services:

  server:
    image: node:6
    command: node server.js
    environment:
      - SERVER_PORT
      - NODE_ENV=${NODE_ENV-development}
    ports:
      - ${DOCKER_PORT:-8080}:${SERVER_PORT:-8080}
    volumes:
      - .:/srv/ascend
    working_dir: /srv/ascend

  dev:
    image: node:6
    command: npm start
    environment:
      - SERVER_PORT
      - NODE_ENV=${NODE_ENV-development}
    ports:
      - ${DOCKER_DEV_PORT:-8081}:${SERVER_DEV_PORT:-8081}
    depends_on:
      - server
    volumes:
      - .:/srv/ascend
    working_dir: /srv/ascend

  build:
    image: node:6
    user: "1000:1000"
    command: npm run build
    volumes:
      - .:/srv/ascend
    working_dir: /srv/ascend

  db:
    image: postgres

  api:
    build: ./apiv2
    command: python3 manage.py runserver 0.0.0.0:${SERVER_PORT:-8080}
    volumes:
      - .:/code
    ports:
      - ${DOCKER_PORT:-8080}:${SERVER_PORT:-8080}
    depends_on:
      - db
