FROM node:6

RUN apt-get update
RUN apt-get install vim -y

ENV APP_DIR /ascend-web

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR
ADD package.json ./
RUN npm install --depth=0 --quiet
RUN npm i -g typescript typings webpack --silent

VOLUME $APP_DIR
EXPOSE 8080

#CMD ["pm2", "start", "server.js", "--no-daemon"]
