version: '3'

services:

  server:
    image: node:6
    command: node server.js
    environment:
      - SERVER_PORT
      - NODE_ENV
    ports:
      - ${DOCKER_PORT:-8080}:${SERVER_PORT:-8080}
    volumes:
      - .:/srv/ascend
    working_dir: /srv/ascend

  dev:
    image: node:6
    command: npm start
    environment:
      - NODE_ENV
    ports:
      - ${DOCKER_DEV_PORT:-8081}:${PORT:-8081}
    depends_on:
      - api
    volumes:
      - .:/srv/ascend
    working_dir: /srv/ascend

  build:
    image: node:6
    user: ${DOCKER_USER-1000}:${DOCKER_USER-1000}
    command: npm run build
    volumes:
      - .:/srv/ascend
    working_dir: /srv/ascend

  db:
    image: postgres
    tty: true

  api:
    image: registry.ascendntnu.no/web-api:2.0
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - ${DOCKER_API_PORT:-8082}:8000
    entrypoint: /code/docker-setup.sh
    tty: true

