version: '3'

services:
  server:
    image: node:6
    command: node server.js
    environment:
      - SERVER_PORT
      - NODE_ENV=${NODE_ENV-development}
    ports:
      - ${DOCKER_PORT:-8080}:${SERVER_PORT:-8080}
    volumes:
      - .:/srv/ascend
    working_dir: /srv/ascend
