# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(default='post', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('categories', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('blog_content', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image_url', models.CharField(max_length=150)),
                ('tags', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('background', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('active_member', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('main', 'Main'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=50)),
                ('url_to_website', models.CharField(max_length=150)),
                ('url_to_logo', models.CharField(max_length=150)),
                ('short_text', models.TextField()),
                ('sign_year', models.DateField()),
            ],
        ),
    ]
