# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 16:54
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(default='post', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('categories', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('blog_content', models.CharField(max_length=400)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('post', models.CharField(blank=True, max_length=150, null=True)),
                ('tags', models.CharField(max_length=150)),
                ('categories', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('background', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('active_member', models.BooleanField(default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('main', 'main'), ('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze')], max_length=50, null=True)),
                ('link', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('logo_dark', models.CharField(blank=True, max_length=100, null=True)),
                ('short_text', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='member',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_member_search__e79da5_gin'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_blogpos_search__ab2950_gin'),
        ),
    ]
