# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 15:46
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='member',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_member_search__e79da5_gin'),
        ),
    ]
