# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180106_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='tags',
            field=models.CharField(max_length=150),
        ),
    ]
