# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trigram_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='image_url',
            new_name='image',
        ),
    ]
