# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180110_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='url_to_logo',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='url_to_website',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='link',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_dark',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='short_text',
            field=models.TextField(default='main'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('main', 'Main'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='main', max_length=50),
        ),
    ]
