# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180110_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo_dark',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='short_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('main', 'Main'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=50),
        ),
    ]
